### ISSUE TITLE
Offset view broken by certain engines

### ISSUE THREAD

**Issue by Starstrider42** [linuxgurugamer/KronalVesselViewer#11]
KSP Version: 1.4.5 64-bit
OS Version: Windows 10
Mod Version: 0.0.9.2

I've frequently run into a bug where KVV's offset view offsets the capsule, but does not offset the upper stage engine or anything below it. The bug is most pronounced with Rockomax engines, where there seems to be no workaround; it also happens with the LV series engines but can be worked around by manually disabling the engine shroud. The bug is accompanied by exceptions like:

    [EXC 20:29:36.263] MissingFieldException: Field '.ModuleJettison.jettisonTransform' not found.
    	KronalUtils.VesselElementViewOptions.Apply (.Part part)
    	KronalUtils.VesselViewConfig.Execute (IShipconstruct ship)
    	KronalUtils.KVrVesselShot.Explode ()
    	KronalUtils.KVrVesselShotUI.GUIButtons ()
    	KronalUtils.KVrVesselShotUI.GUIWindow (Int32 id)
    	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
    	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)

The easiest way to reproduce the issue is to start a sandbox game, load the Kerbal X, and try to display it in KVV in offset mode. See the screenshot below (taken with default settings) or [the log](https://gist.github.com/Starstrider42/427da5d3f27b4d37d716e7d13f252241).

![Kerbal X in KVV](https://user-images.githubusercontent.com/6760782/45858849-2d314780-bd14-11e8-941f-8deb4cbf3c6c.png)

**Comment by Kerbas-ad-astra** [comment]
I get that issue when I use linuxgurugamer's release builds, but when I compile the DLL myself (release, debug, or DebugNoProceduralFairingsKAS), I get a DLL that is 80-86 kb (vs. 58 kb from LGG) and have no problems with the Kerbal X.

**Comment by linuxgurugamer** [comment]
I can confirm this, I need to figure out why my builds are broken.  I'll get a working one uploaded this evening

**Comment by linuxgurugamer** [comment]
I've done  a manual build and upload, 0.0.9.5, which fixes this problem.

**Comment by Starstrider42** [comment]
Sorry, I'm still getting the same problem with version 0.0.9.5 (which I confirm is 80 kiB). Building my own copy like @Kerbas-ad-astra described does work.

Given the hard dependencies on KAS and Procedural Fairings in the code, I should add that the official build does not work even if those two mods are installed, and that the local one works even if they are not.

**Comment by linuxgurugamer** [comment]
That is very odd, since the 0.0.9.5 was a manual build.
I just installed 0.0.9.5 using CKAN into a new build, and it worked.  I did not have either KAS or ProceduralFairings installed.
Can you please upload a log file so I can see what's different?

**Comment by linuxgurugamer** [comment]
Is it possible that you have the old dll somewhere in your install?

**Comment by Starstrider42** [comment]
Here's a [new log](https://gist.github.com/Starstrider42/64186ed8c395ed108f14d7e349298568), with the KSP install made as clean as possible. In particular, I checked that there's no other `KronalUtils.dll` anywhere in the KSP directory.

**Comment by linuxgurugamer** [comment]
Ok, I found the problem.
Seems that the API changed slightly:
in 1.4.3, the following:
`public Transform jettisonTransform;`
and in 1.4.5:
`public Transform jettisonTransform { get; set; }`
 
So, no code changes are required, but the mod does need to be rebuilt.

I've released two new versions, 0.0.9.6 for KSP 1.4.3, and 0.0.9.7 for KSP 1.4.5

**Comment by Starstrider42** [comment]
You'd think they'd know better than to change a public API like that... 🙁 

I confirm the fix works both on a clean install and in my main save. Thanks for the quick response!

**Comment by linuxgurugamer** [comment]
It happens, and sometimes there are good reasons for it
Glad it's fixed

**Comment by linuxgurugamer** [comment]
@Kerbas-ad-astra  @Starstrider42  I've fixed the problem on my Jenkins server.  The dll is still only 58k in size, but it work for me on 1.4.5.
I'd appreciate it if you would both download and test this version:
https://github.com/linuxgurugamer/KronalVesselViewer/releases/tag/0.0.9.8

**Comment by Kerbas-ad-astra** [comment]
Works for me as well.

**Comment by Starstrider42** [comment]
Confirmed, it still works.

**Comment by linuxgurugamer** [comment]
Great, thanks for testing
