### ISSUE TITLE
You need to update the shader load path for the folder change.

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [linuxgurugamer/KronalVesselViewer#9]
[Over here.](https://github.com/linuxgurugamer/KronalVesselViewer/blob/7a47d5439544e524835efcc383a69bc8be8157d3/KronalVesselViewer/MaterialProperties.cs#L194)

[And the button texture path as well.](https://github.com/linuxgurugamer/KronalVesselViewer/blob/7a47d5439544e524835efcc383a69bc8be8157d3/KronalVesselViewer/KVrVesselShotUI.cs#L448)

**Comment by linuxgurugamer** [comment]
Oh, ok, will get to it this evening,
Thanks

**Comment by linuxgurugamer** [comment]
That will teach me to code when exhausted.
thanks it's fixed (I hope).

**Comment by Kerbas-ad-astra** [comment]
Apologies, I missed one: https://github.com/linuxgurugamer/KronalVesselViewer/blob/master/KronalVesselViewer/BundleIndex.cs#L92

**Comment by linuxgurugamer** [comment]
Ok, fixing it now, thanks
